[build]
command = "npm run build"
publish = ".output/public"
functions = ".output/server/netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Для обработки API-роутов
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200